package tournament;

public enum FIFASoccerTeam {
	ALGERIA, ANGOLA, ARGENTINA, AUSTRALIA, AUSTRIA, BELGIUM, BOLIVIA, BOSNIA_HERZEGOVINA, BRAZIL, BULGARIA,USA,
	CHILE, COLOMBIA, URUGUAY, FRANCE, NIGERIA, GERMANY, NETHERLANDS, MEXICO, COSTA_RICA, GREECE, SLOVAKIA, SWITZERLAND,
}
